# Generated by Django 5.2 on 2025-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pitching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.DateField(null=True)),
                ("pitch_type", models.CharField(blank=True, max_length=10, null=True)),
                ("release_speed", models.FloatField(blank=True, null=True)),
                ("release_spin_rate", models.FloatField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                ("plate_x", models.FloatField(blank=True, null=True)),
                ("plate_z", models.FloatField(blank=True, null=True)),
                ("pfx_x", models.FloatField(blank=True, null=True)),
                ("pfx_z", models.FloatField(blank=True, null=True)),
                ("pitch_number", models.IntegerField(blank=True, null=True)),
                ("inning", models.IntegerField(blank=True, null=True)),
                ("outs_when_up", models.IntegerField(blank=True, null=True)),
                ("batter", models.IntegerField(blank=True, null=True)),
                ("events", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="student",
        ),
    ]
