# Generated by Django 5.2 on 2025-05-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_pitching_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitching",
            name="at_bat_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pitching",
            name="game_pk",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="pitching",
            unique_together={("game_pk", "at_bat_number", "pitch_number")},
        ),
    ]
